name: Build devcontainer image and push to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'uv.lock'
      - 'pyproject.toml'
      - '.devcontainer/Dockerfile'
  workflow_dispatch:
    inputs:
      trigger_reason:
        type: string
        description: 'Enter reason for manually triggering devcontainer build:'
        required: true

env:
  CONTAINER_REPOSITORY: "jpsachs/scihfs-devcontainer"

jobs:
  build-and-push-devcontainer-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get 7-digit commit hash for versioning of the uploaded container images
        run: echo "COMMIT_HASH_SHORT=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push devcontainer image
        uses: docker/build-push-action@v7
        with:
          file: .devcontainer/Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.CONTAINER_REPOSITORY }}:${{ env.COMMIT_HASH_SHORT }}
            ${{ env.CONTAINER_REPOSITORY }}:latest
          platforms: linux/amd64,linux/arm64
          provenance: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
