# Runs this job for pull requests and manual triggers.

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "doc/**"
      - "LICENSE"
      - ".gitignore"
      - ".devcontainer/**"
      - ".pre-commit-config.yaml"
      - ".readthedocs.yaml"
      - "Makefile"
  workflow_dispatch:

jobs:
  lint:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          # cannot use use_pyproject to use settings from pyproject.toml below python 3.11
          options: "--line-length 90 scihfs"
  test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest scihfs --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  minimum-versions:
    name: Run tests (for minimum supported versions)
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python 3.10 (scihfs current lower bound)
        run: uv python install 3.10

      - name: Install minimum supported versions for direct dependencies
        run: uv sync --resolution lowest-direct --python 3.10

      - name: Run tests
        run: uv run --no-sync pytest scihfs

  maximum-stable-versions:
    name: Run tests (maximum stable versions)
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python 3.14 (scihfs current upper bound)
        run: uv python install 3.14

      - name: Install maximum stable versions for all dependencies
        run: uv sync --upgrade --python 3.14

      - name: Run tests
        run: uv run --no-sync pytest scihfs
